### ISSUE TITLE
GetDeviceCertificate incorrectly drops untrusted certificate errors

### ISSUE THREAD

**Issue by riverar** [Microsoft/WindowsDevicePortalWrapper#145]
If a user was being MITM'd, this could potentially hide that fact and insecurely leak credentials to a third party.

https://github.com/Microsoft/WindowsDevicePortalWrapper/blob/master/WindowsDevicePortalWrapper/WindowsDevicePortalWrapper.UniversalWindows/CertificateHandling.cs#L51

Instead, the wrapper must present the cert and require manual trust.

**Comment by davidkline-ms** [comment]
the .net implementation needs improvement in this area as well.

**Comment by WilliamsJason** [comment]
I may be able to address this with some readme changes and overall manual specified cert changes related to my recent change for enabling Fiddler or another Web proxy (essentially just a MITM).

I'll follow up shortly with this.
