### ISSUE TITLE
Make set in each data contract private and update docs

### ISSUE THREAD

**Issue by hpsin** [Microsoft/WindowsDevicePortalWrapper#159]

**Comment by davidkline-ms** [comment]
i have this in progress.

**Comment by WilliamsJason** [comment]
:/ we crossed streams. Mind integrating in what I have and then just making sure I didn't miss anything?

**Comment by davidkline-ms** [comment]
never cross the streams!!! :)

closed with #159

**Comment by WilliamsJason** [comment]
I ran the script to update the docs as well. Looks much cleaner now when looking at the data contracts. We'll want to update again after moving around namespaces.
