### ISSUE TITLE
Rebooting a device leads to a bad CSRF token if the next call is not a GET call

### ISSUE THREAD

**Issue by WilliamsJason** [Microsoft/WindowsDevicePortalWrapper#166]
We should detect the bad token case and make a trivial GET call before retrying automatically. The error message will always be "CSRF Token Invalid".

**Comment by davidkline-ms** [comment]
I've been thinking on this one for awhile. we could mark the DevicePortalConnection object has having had it's device restarted / connection lost and have the app do a simple get (like a heartbeat) or a full re-connect.

thoughts?

**Comment by GregPettyjohn** [comment]
I originally found this while developing my sample (not merged yet.) But it is also possible to reproduce using the XboxWdpDriver.

Here are the arguments I used:
/x:<devkit ip> /user:<username> /pwd:<password> /thumbprint:<big hex number> /op:reboot

(If you don't know the thumbprint, just run the command one time without a thumbprint specified and it will give you a value to use subsequently.)
