### ISSUE TITLE
CSRF refresh then retry doesn't work if the PUT request has a body

### ISSUE THREAD

**Issue by WilliamsJason** [Microsoft/WindowsDevicePortalWrapper#173]
POST probably suffers from the same bug. The body has already been disposed and can't be reused for a retry.

I can probably move the retry up a level to get around this.

**Comment by hpsin** [comment]
I worry that it will be confusing to implicitly retry in some cases and in others return an error saying they need to manually retry. 

At the same time, I'm guessing we lose out on the benefits of the async pattern if we move this up a layer and hold onto the body until we get a response. Good catch Jason, thanks.
