### ISSUE TITLE
Async suffix required for all asynchronous methods

### ISSUE THREAD

**Issue by jbienzms** [Microsoft/WindowsDevicePortalWrapper#183]
According to [Asynchronous Programming with async and await](https://msdn.microsoft.com/en-us/library/mt674882.aspx):

> "By convention, you append "Async" to the names of methods that have an async modifier."

I do not see any asynchronous methods that return Task in this library named with the "Async" suffix.

**Comment by hpsin** [comment]
Thanks Jared, 
This would constitute a breaking change to the library, which is hard to justify usually.  We're still pre-1.0 release, but given the amount written with the library thus far and that this is only a convention, I don't feel it's a worthwhile breaking change.  

I'm curious to see what other folks' feelings are on this, so I'll leave this open and request that they weigh in.

**Comment by hpsin** [comment]
After discussion, we should do the breaking change before the 1.0 release. Investigating.

**Comment by hpsin** [comment]
Fixed by #188
