### ISSUE TITLE
Files inside CameraRoll are falsely marked as directories

### ISSUE THREAD

**Issue by Holo-Krzysztof** [Microsoft/WindowsDevicePortalWrapper#205]
When listing the contents of the CameraRoll folder on HoloLens, the ToString method in [AppFileExplorer.cs](https://github.com/Microsoft/WindowsDevicePortalWrapper/blob/cfa914481d1aef81ae8a40c2d177e331cd0947b9/WindowsDevicePortalWrapper/WindowsDevicePortalWrapper.Shared/Core/AppFileExplorer.cs#L324) makes files appear as directories because SubPath is null while CurrentDir is an empty string.

My current workaround workaround looks like this:
```
private bool IsFolder(FileOrFolderInformation item)
{
    if (!string.IsNullOrEmpty(item.SubPath) && !string.Equals(item.SubPath, item.CurrentDir))
    {
        return true;
    }
    return false;
}
```

I'm doing that in my application code, though. Could anyone verify that it works? If it does, I could make the change to the line mentioned above.

**Comment by hpsin** [comment]
@WilliamsJason , can we use type here instead for the <DIR> check? It's a poorly documented Windows enum, but should reliably say if it's a folder.

**Comment by WilliamsJason** [comment]
Sure. It looks like in the ToString method I did the same thing (checking to see if SubPath and CurrentDir match) but Type should be more reliable. I'll add an IsFolder method to FileOrFolderInformation.

**Comment by hpsin** [comment]
Should be fixed now - thanks for letting us know, sorry for the annoyance!
