### ISSUE TITLE
If using HTTPS without requiring authentication, non-GET calls fail due to CSRF.

### ISSUE THREAD

**Issue by WilliamsJason** [Microsoft/WindowsDevicePortalWrapper#206]
We are using the CSRF bypass mechanism now (prepending 'auto-' to the username), but if authentication is not required then this doesn't work and CSRF still blocks us.

We might need to bring back the code we used to have which handled CSRF cookies and fix any issues that crop up from that.

**Comment by hpsin** [comment]
The auto- not working is a Device Portal bug, server side, which we're investigating for a fix in the Creators Update.  In order to get the wrapper working with Anniversary Update (14393) we should investigate further.
