### ISSUE TITLE
There is no way to check a package's origin.

### ISSUE THREAD

**Issue by Holo-Krzysztof** [Microsoft/WindowsDevicePortalWrapper#208]
The [Device Portal Core API reference](https://msdn.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core) lists a "PackageOrigin" property under `/api/app/packagemanager/packages`, but I have not seen it anywhere in the wrapper (more specifically, inside `PackageInfo`)

The problem is, I'm listing the installed packages so the user can upload to LocalAppData inside her own packages, but it also lists the preinstalled ones from Microsoft, which I cannot open with `GetFolderContentsAsync()`.

**Comment by hpsin** [comment]
Fixed with #210, thanks @WilliamsJason !
