### ISSUE TITLE
DevicePortalConnection fails when device is connected via USB, but has an active wifi connection.

### ISSUE THREAD

**Issue by Holo-Krzysztof** [Microsoft/WindowsDevicePortalWrapper#209]
I've observed this behavior on HoloLens, so I don't know if this affects other devices as well, but if the HoloLens is connected to WLAN and via USB to a PC, attempting a connection via 127.0.0.1:10080 fails. The connection status says "connected", but after that I get a bunch of exceptions. I've printed out the status on the ConnectionChanged event, here's the output:

```
DeterminingConnectionRequirements Connecting Checking secure connection requirements
UpdatingDeviceAddress Connecting Updating device connection
Idle Connected Device connection established
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.dll
Exception thrown: 'System.Security.Authentication.AuthenticationException' in System.dll
Exception thrown: 'System.ObjectDisposedException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in mscorlib.dll
An error occurred while sending the request.
Exception thrown: 'System.Net.Http.HttpRequestException' in WpfDevicePortal.exe
```

I've observed that somewhere in the connection process DevicePortal.Address (which is 127.0.0.1:10080 initially) is replaced with the address of the access point the HoloLens is connected to. Does anyone know why this is happening?

**Comment by hpsin** [comment]
This is due to the updateConnection bool being set to true by default on the connectAsync method in DevicePortal.cs: https://github.com/Microsoft/WindowsDevicePortalWrapper/blob/master/WindowsDevicePortalWrapper/WindowsDevicePortalWrapper.Shared/DevicePortal.cs#L252 

Can you try changing your code to call portal.ConnectAsync(**updateConnection:false**); 
This should stop your HoloLens from attempting to pick up the WiFi connection

**Comment by davidkline-ms** [comment]
@Holo-Krzysztof, Would an API (breaking) change to support; Update, Don't Update, Try to update (aka return localhost if cannot connect to wifi) be helpful here?

**Comment by davidkline-ms** [comment]
@hpsin,
I'd need to see the contents of the HttpRequestException and what IP the portal was attempting to connect to.

**Comment by davidkline-ms** [comment]
@Holo-Krzysztof, is your app able to successfully talk to the HoloLens via the localhost (usb) connection? Also, can you double check that the IP address that the wrapper is attempting to connect to is valid (ex: not 0.0.0.0 or something weird) and post the exception contents (feel free to obfuscate the ip address)?

Thanks!

**Comment by Holo-Krzysztof** [comment]
@hpsin Thanks, that fixed it. The problem was that I always connected via USB and didn't know what "updateConnection" means in that context or why it is done.

@davidkline-ms I don't get more than what I've posted above, it doesn't catch an exception when wrapping the call to ConnectAsync inside a try-catch block (using the dll version via nuget). I assume the exception is handled within the library itself and not propagated upwards.

Yes, I can successfully connect via USB and yes, it is a valid address. It's exactly the address of the HoloLens inside the local network (10.0.0.28 when I checked).

**Comment by davidkline-ms** [comment]
@Holo-Krzysztof,
You may be able to get more information by enabling the debugger to break on first chance exceptions when you hit the HttpRequestException.

To do this, load your project and go to Debug | Windows | Exception Settings, expand Common Language Runtime Exceptions and check <All Common Language Runtime Exceptions not in this list>. You may have to continue on past a few unrelated exceptions, but this should help diagnose what is going wrong.

Thanks!

**Comment by hpsin** [comment]
Basically this bug will hit you any time you connect over USB to a device that's not on the same local network.  It's to help the HoloLens/phone teams plugin a device over USB, get a connection via Wifi to it, and then unplug the device while retaining the connection, thus allowing you to rapidly setup multiple devices from a "home base".  

We should probably change the default to false. @davidkline-ms , would that break any scenarios on your end?

**Comment by davidkline-ms** [comment]
@hpsin, THAT makes sense. Changing the default wont break scenarios, I would just need to explicitly specify true.

Any thoughts on making the parameter a tristate with the default being "TryToChange"?
