### ISSUE TITLE
Generate updated NuGet package

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/WindowsDevicePortalWrapper#217]
Given PR #215's improvements and other recent changes (PR #213, #211) we should create an updated NuGet package so that clients can easily take advantage of the fixes and additions

**Comment by dotMorten** [comment]
If you do that, do you mind including the XML doc too? Really annoying not getting intellisense. Especially now that it's actually all documented.

**Comment by hpsin** [comment]
Great suggestion - I'll look up how to add those docs. 
@davidkline-ms  - I want to get the ETW API working with arbitrary payloads before a new release.  That said, yes, absolutely.

**Comment by dotMorten** [comment]
Just check on "xml documentation" in the build settings. In the nuget package, all you need to do is place the .xml file next to the .dll.

![image](https://cloud.githubusercontent.com/assets/1378165/23002034/4893cd64-f39d-11e6-839e-4b6456f70ead.png)

**Comment by hpsin** [comment]
This was done with v0.9.4
