### ISSUE TITLE
Provide a discovery API

### ISSUE THREAD

**Issue by dotMorten** [Microsoft/WindowsDevicePortalWrapper#219]
The IoT Core Dashboard app auto-discovers devices on the network with the DevicePortal enabled.
It would be really useful if this API also has a way to auto-discover devices.
There's a repo here that works for 10240 and 10586, but unfortunately doesn't work fro 14393+:
https://github.com/emmellsoft/WinIoTCoreListener

 The protocol for discovering the devices isn't documented though, so it would be good with a more "official" API in here for this.

**Comment by hpsin** [comment]
Is this the same as #32 ? We document the DNS-SD service advertisement here: https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal#service-features-and-notes

**Comment by dotMorten** [comment]
Thanks! yes. sorry I should have looked harder
