### ISSUE TITLE
PCs/Laptops/Tablets should be DevicePortalPlatforms.Windows not DevicePortalPlatforms.Unknown

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/WindowsDevicePortalWrapper#227]
the platformname returned by the Windows Device Portal is generally descriptive of the PC (ex: laptop model) which results in the platform being returned as Unknown instead of Windows.

**Comment by hpsin** [comment]
Honestly, using OsEditionId might make more sense - then you should just get Windows.Desktop | Windows.Xbox | Windows.HoloLens etc.

**Comment by davidkline-ms** [comment]
resolved with commit 0e5f200. apologies for accidentally bypassing the PR process. other admins have subsequently reviewed the change
