### ISSUE TITLE
install should use StorageFile instead of file name to access files [UWP dll]

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/WindowsDevicePortalWrapper#228]
BREAKING CHANGE

Applications cannot open arbitrary files by name. Users can navigate to desired files using the FilePicker which returns a StorageFile.

**Comment by hpsin** [comment]
How easy is it to convert a file embedded in a UWP (e.g. someone puts all of their dependencies in the appx) to a StorageFile?

**Comment by davidkline-ms** [comment]
I should have clarified this a bit more...

in the uwp version of the wdpw dll, the appinstall code path should consume StorageFile objects instead of strings (file name) when accessing the files. uwp has rules related to files that can be opened (and from where) when using arbitrary paths. using the FilePicker (returns StorageFile) avoids many of these issues.

client applications just need to use the FilePicker to select files and pass the returned objects to WDPW's uwp dll when this is fixed.

**Comment by davidkline-ms** [comment]
resolved with commit 0e5f200. apologies for accidentally bypassing the PR process. other admins have subsequently reviewed the change
