### ISSUE TITLE
Provide option to use the certificate store when connecting

### ISSUE THREAD

**Issue by davidkline-ms** [Microsoft/WindowsDevicePortalWrapper#249]
If a user installs the device certificate, there is no need to retrieve it for each connection attempt unless the certificate changes.

**Comment by hpsin** [comment]
Hey Dave,
Is the goal here that if the user has trusted the root cert, WDP Wrapper automatically accepts the cert? I believe that's the standard behavior in UWP/.NET.

**Comment by davidkline-ms** [comment]
Duh. I was meaning to log this in the HoloLensCompanionKit... :)
