### ISSUE TITLE
Using DeleteFileAsync on Hololens crashes with filenames that contain ampersands

### ISSUE THREAD

**Issue by gjrgj** [Microsoft/WindowsDevicePortalWrapper#261]
I'm not sure if other special characters trigger this as well as I haven't tested it. However, uploading these files works fine with UploadFileAsync, yet for some reason deletion is bugged.

**Comment by hpsin** [comment]
URIs really don’t like ampersands in them, as they denote a new query parameter. My guess is that this is a bug in the Device Portal UI as well and a bug in general in the rest api. I'll investigate more today and get back to you, thanks George

Sent from my Windows 10 phone

**Comment by gjrgj** [comment]
Thanks for the prompt reply @hpsin !

**Comment by hpsin** [comment]
Thanks George - it looks like the WDP UI does some URL Encoding, converting the & into %26.  I'm working on a fix now to do the same in File Explorer.

**Comment by hpsin** [comment]
And it should be fixed! Also impacted the GET API, so you hit a two for one here :) 

Thanks! Let me know if you want a point release for this fix or if it's good enough in the lib.

**Comment by gjrgj** [comment]
Awesome! Thanks so much @hpsin - and this is good enough in the lib, no worries.
