### ISSUE TITLE
Multiple Warnings from 'StyleCopTask' task 

### ISSUE THREAD

**Issue by ryzngard** [Microsoft/WindowsDevicePortalWrapper#277]
When pulling and building the source, I have multiple of the below error.  

| Severity	| Code | Description	| Project | File | Line | Suppression State |
|-----------|-------|-------------|---------|-----|------|---------------------|
| Error |  | The "StyleCopTask" task could not be loaded from the assembly C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\..\StyleCop 4.7\StyleCop.dll. Could not load file or assembly 'file:///C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\StyleCop 4.7\StyleCop.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. | XboxWdpDriver | C:\Program Files (x86)\MSBuild\StyleCop\v4.7\StyleCop.targets	| 98	| Error |	

Full build log below from re-build [build.txt](https://github.com/Microsoft/WindowsDevicePortalWrapper/files/1489069/build.txt)

**Comment by hpsin** [comment]
@WilliamsJason - is there a way to make stylecop optional in this project? I believe it's optional for the rest of the solution. 

@ryzngard - this should just work, we point to the StyleCop via the registry, can you check this key? HKLM\Software\CodePlex\StyleCop TargetsDir ? Looks like it's finding your Enterprise install of VS 2017 and then not finding Stylecop.  Might just have to install it.

**Comment by WilliamsJason** [comment]
I thought we'd made it optional :/

@MattHyman was mentioning you can add StyleCop as a NuGet dependency. We should switch to that, it should avoid forcing people to manually install it (or not install it and miss warnings that we should be fixing).

**Comment by MattHyman** [comment]
I tried the nuget version, at least for me it did not work with the UWP projects.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by WilliamsJason** [comment]
I'm going to turn off StyleCop build integration. Maybe we can eventually sort out the NuGet package but for now everyone running StyleCop will need to run it via 'Tools->Run StyleCop' since the build integration seems to be having issues when StyleCop is installed.
