### ISSUE TITLE
ETW APIs are unimplemented

### ISSUE THREAD

**Issue by hpsin** [Microsoft/WindowsDevicePortalWrapper#31]
The ETW collection APIs for Core are unimplemented. 
The stub file is in Shared/Core/Etw.cs
Docs for the ETW collection APIs can be found on [MSDN](https://msdn.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core#etw)

**Comment by davidkline-ms** [comment]
closed by pr #213
